/*
===========================================================================
Copyright (C) 1997-2001 Id Software, Inc.

This file is part of Quake 2 source code.

Quake 2 source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake 2 source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Quake 2 source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/

	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"QUAKE II MISSION PACK: THE RECKONING",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"BY",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"XATRIX ENTERTAINMENT, INC.",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"DESIGN AND DIRECTION",
	"Drew Markham",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"PRODUCED BY",
	"Greg Goodrich",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"PROGRAMMING",
	"Rafael Paiz",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"LEVEL DESIGN / ADDITIONAL GAME DESIGN",
	"Alex Mayberry",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"LEVEL DESIGN",
	"Mal Blackwell",
	"Dan Koppel",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ART DIRECTION",
	"Michael \"Maxx\" Kaufman",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"COMPUTER GRAPHICS SUPERVISOR AND",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"CHARACTER ANIMATION DIRECTION",
	"Barry Dempsey",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"SENIOR ANIMATOR AND MODELER",
	"Jason Hoover",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"CHARACTER ANIMATION AND",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"MOTION CAPTURE SPECIALIST",
	"Amit Doron",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ART",
	"Claire Praderie-Markham",
	"Viktor Antonov",
	"Corky Lehmkuhl",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"INTRODUCTION ANIMATION",
	"Dominique Drozdz",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ADDITIONAL LEVEL DESIGN",
	"Aaron Barber",
	"Rhett Baldwin",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"3D CHARACTER ANIMATION TOOLS",
	"Gerry Tyra, SA Technology",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ADDITIONAL EDITOR TOOL PROGRAMMING",
	"Robert Duffy",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ADDITIONAL PROGRAMMING",
	"Ryan Feltrin",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"PRODUCTION COORDINATOR",
	"Victoria Sylvester",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"SOUND DESIGN",
	"Gary Bradfield",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"MUSIC BY",
	"Sonic Mayhem",
	"",
	"",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"SPECIAL THANKS",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"TO",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"OUR FRIENDS AT ID SOFTWARE",
	"",
	"John Carmack",
	"John Cash",
	"Brian Hook",
	"Adrian Carmack",
	"Kevin Cloud",
	"Paul Steed",
	"Tim Willits",
	"Christian Antkow",
	"Paul Jaquays",
	"Brandon James",
	"Todd Hollenshead",
	"Barrett (Bear) Alexander",
	"Dave \"Zoid\" Kirsch",
	"Donna Jackson",
	"",
	"",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"THANKS TO ACTIVISION",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"IN PARTICULAR:",
	"",
	"Marty Stratton",
	"Henk \"The Original Ripper\" Hartong",
	"Kevin Kraff",
	"Jamey Gottlieb",
	"Chris Hepburn",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"AND THE GAME TESTERS",
	"",
	"Tim Vanlaw",
	"Doug Jacobs",
	"Steven Rosenthal",
	"David Baker",
	"Chris Campbell",
	"Aaron Casillas",
	"Steve Elwell",
	"Derek Johnstone",
	"Igor Krinitskiy",
	"Samantha Lee",
	"Michael Spann",
	"Chris Toft",
	"Juan Valdes",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"THANKS TO INTERGRAPH COMPUTER SYTEMS",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"IN PARTICULAR:",
	"",
	"Michael T. Nicolaou",
	"",
	"",
	"Quake II Mission Pack: The Reckoning",
	"(tm) (C)1998 Id Software, Inc. All",
	"Rights Reserved. Developed by Xatrix",
	"Entertainment, Inc. for Id Software,",
	"Inc. Distributed by Activision Inc.",
	"under license. Quake(R) is a",
	"registered trademark of Id Software,",
	"Inc. Quake II Mission Pack: The",
	"Reckoning(tm), Quake II(tm), the Id",
	"Software name, the \"Q II\"(tm) logo",
	"and id(tm) logo are trademarks of Id",
	"Software, Inc. Activision(R) is a",
	"registered trademark of Activision,",
	"Inc. Xatrix(R) is a registered",
	"trademark of Xatrix Entertainment,",
	"Inc. All other trademarks and trade",
	"names are properties of their",
	"respective owners.",
	0
