/*
===========================================================================
Copyright (C) 1997-2001 Id Software, Inc.

This file is part of Quake 2 source code.

Quake 2 source code is free software; you can redistribute it
and/or modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of the License,
or (at your option) any later version.

Quake 2 source code is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Quake 2 source code; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
===========================================================================
*/

	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"QUAKE II MISSION PACK 2: GROUND ZERO",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"BY",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ROGUE ENTERTAINMENT, INC.",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"PRODUCED BY",
	"Jim Molinets",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"PROGRAMMING",
	"Peter Mack",
	"Patrick Magruder",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"LEVEL DESIGN",
	"Jim Molinets",
	"Cameron Lamprecht",
	"Berenger Fish",
	"Robert Selitto",
	"Steve Tietze",
	"Steve Thoms",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ART DIRECTION",
	"Rich Fleider",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ART",
	"Rich Fleider",
	"Steve Maines",
	"Won Choi",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ANIMATION SEQUENCES",
	"Creat Studios",
	"Steve Maines",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"ADDITIONAL LEVEL DESIGN",
	"Rich Fleider",
	"Steve Maines",
	"Peter Mack",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"SOUND",
	"James Grunke",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"GROUND ZERO THEME",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"AND",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"MUSIC BY",
	"Sonic Mayhem",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"VWEP MODELS",
	"Brent \"Hentai\" Dill",
	"",
	"",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"SPECIAL THANKS",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"TO",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"OUR FRIENDS AT ID SOFTWARE",
	"",
	"John Carmack",
	"John Cash",
	"Brian Hook",
	"Adrian Carmack",
	"Kevin Cloud",
	"Paul Steed",
	"Tim Willits",
	"Christian Antkow",
	"Paul Jaquays",
	"Brandon James",
	"Todd Hollenshead",
	"Barrett (Bear) Alexander",
	"Katherine Anna Kang",
	"Donna Jackson",
	"Dave \"Zoid\" Kirsch",
	"",
	"",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"THANKS TO ACTIVISION",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"IN PARTICULAR:",
	"",
	"Marty Stratton",
	"Henk Hartong",
	"Mitch Lasky",
	"Steve Rosenthal",
	"Steve Elwell",
	"",
	S_COLOR_BOLD S_COLOR_SHADOW S_COLOR_ALT"AND THE GAME TESTERS",
	"",
	"The Ranger Clan",
	"Dave \"Zoid\" Kirsch",
	"Nihilistic Software",
	"Robert Duffy",
	"",
	"And Countless Others",
	"",
	"",
	"",
	"Quake II Mission Pack 2: Ground Zero",
	"(tm) (C)1998 Id Software, Inc. All",
	"Rights Reserved. Developed by Rogue",
	"Entertainment, Inc. for Id Software,",
	"Inc. Distributed by Activision Inc.",
	"under license. Quake(R) is a",
	"registered trademark of Id Software,",
	"Inc. Quake II Mission Pack 2: Ground",
	"Zero(tm), Quake II(tm), the Id",
	"Software name, the \"Q II\"(tm) logo",
	"and id(tm) logo are trademarks of Id",
	"Software, Inc. Activision(R) is a",
	"registered trademark of Activision,",
	"Inc. Rogue(R) is a registered",
	"trademark of Rogue Entertainment,",
	"Inc. All other trademarks and trade",
	"names are properties of their",
	"respective owners.",
	0
